// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckgdamhpwuvegkfieyyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZ2RhbWhwd3V2ZWdrZmlleXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3MTkwOTksImV4cCI6MjA1MjI5NTA5OX0.l-4V8Zd2E55y3ahbp_NUicct2m4HOutGwxCALd6YGDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);